package com.qst.entity;
// Generated 2019-8-5 19:53:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbAdmin generated by hbm2java
 */
@Entity
@Table(name = "tb_admin")
public class TbAdmin implements java.io.Serializable {

	private int id;
	private String account;
	private String pwd;
	private Integer status;

	public TbAdmin() {
	}

	public TbAdmin(int id) {
		this.id = id;
	}

	public TbAdmin(int id, String account, String pwd, Integer status) {
		this.id = id;
		this.account = account;
		this.pwd = pwd;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "account")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "pwd")
	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "TbAdmin [id=" + id + ", account=" + account + ", pwd=" + pwd + ", status=" + status + "]";
	}
	
	

}
