package com.qst.entity;
// Generated 2019-8-10 14:53:51 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BtBrowshistory generated by hbm2java
 */
@Entity
@Table(name = "bt_browshistory")
public class TbBrowshistory implements java.io.Serializable {

	private int id;
	private Integer UId;
	private Integer PId;
	private Date createTime;
	private Integer stayTime;

	public TbBrowshistory() {
	}

	public TbBrowshistory(int id) {
		this.id = id;
	}

	public TbBrowshistory(int id, Integer UId, Integer PId, Date createTime, Integer stayTime) {
		this.id = id;
		this.UId = UId;
		this.PId = PId;
		this.createTime = createTime;
		this.stayTime = stayTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "u_id")
	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	@Column(name = "p_id")
	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_time", length = 10)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "stay_time")
	public Integer getStayTime() {
		return this.stayTime;
	}

	public void setStayTime(Integer stayTime) {
		this.stayTime = stayTime;
	}

}
