package com.qst.entity;
// Generated 2019-8-5 19:53:09 by Hibernate Tools 5.1.10.Final

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.qst.util.JsonUtils;
import com.qst.vo.BusinessInfo;

/**
 * TbCompany generated by hbm2java
 */
@Entity
@Table(name = "tb_company")
public class TbCompany implements java.io.Serializable {

	private int id;
	private String name;
	private String account;
	private String pwd;
	private Integer scale;
	private String tag;
	private String head;
	private String description;
	private String detailAddress;
	private String publicityImg;
	private String businessInfo;
	private String hrName;
	private String chrContec;
	private Date createTime;
	
	private int status;
	
	private BusinessInfo bsi;
	
	private String headerUrl;  //公司头像地址
	private String locationPoint; //公司地址坐标
	private String cTime;
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

	public String getcTime() {
		if(createTime == null)
		{
			return null;
		}
		else{
			return sdf.format(createTime);
		}
		
	}
	
	public void setcTime(String cTime) {
		this.cTime = cTime;
	}

	
	public TbCompany() {
	}

	public TbCompany(int id) {
		this.id = id;
	}

	public TbCompany(int id, String name, Integer scale, String tag, String head, String desc, String publicityImg,
			String businessInfo, String hrName, String chrContec, Date createTime) {
		this.id = id;
		this.name = name;
		this.scale = scale;
		this.tag = tag;
		this.head = head;
		this.description = desc;
		this.publicityImg = publicityImg;
		this.businessInfo = businessInfo;
		this.hrName = hrName;
		this.chrContec = chrContec;
		this.createTime = createTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "scale")
	public Integer getScale() {
		return this.scale;
	}

	public void setScale(Integer scale) {
		this.scale = scale;
	}
	
	public String getScaleStr(){
		if(scale == null){
			return "";
		}
		switch (scale) {
		case 0: return "50人左右";
		case 1: return "100人左右";
		case 2: return "100-500人";
		case 3: return "1000人以上";
		default:
			break;
		}
		return "";
	}

	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Column(name = "head")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String desc) {
		this.description = desc;
	}

	@Column(name = "publicity_img")
	public String getPublicityImg() {
		return this.publicityImg;
	}

	public void setPublicityImg(String publicityImg) {
		this.publicityImg = publicityImg;
	}

	@Column(name = "business_info")
	public String getBusinessInfo() {
		return this.businessInfo;
	}

	public void setBusinessInfo(String businessInfo) {
		if(businessInfo==null || businessInfo.equals(""))
			this.bsi = new BusinessInfo();
		else
			this.bsi = JsonUtils.jsonToPojo(businessInfo, BusinessInfo.class);
		
		this.businessInfo = businessInfo;
	}

	@Column(name = "hr_name")
	public String getHrName() {
		return this.hrName;
	}

	public void setHrName(String hrName) {
		this.hrName = hrName;
	}

	@Column(name = "chr_contec")
	public String getChrContec() {
		return this.chrContec;
	}

	public void setChrContec(String chrContec) {
		this.chrContec = chrContec;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "TbCompany [id=" + id + ", name=" + name + ", scale=" + scale + ", tag=" + tag + ", head=" + head
				+ ", description=" + description + ", publicityImg=" + publicityImg + ", businessInfo=" + businessInfo
				+ ", hrName=" + hrName + ", chrContec=" + chrContec + ", createTime=" + createTime + "]";
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getDetailAddress() {
		return detailAddress;
	}

	public void setDetailAddress(String detailAddress) {
		this.detailAddress = detailAddress;
	}
	
	
	public String[] getTags(){
		if(this.tag != null)
			return this.tag.split(",");
		return new String[]{"可以"};
	}
	
	public String getHeaderUrl() {
		return headerUrl;
	}

	public void setHeaderUrl(String headerUrl) {
		this.headerUrl = headerUrl;
	}

	public String getLocationPoint() {
		return locationPoint;
	}

	public void setLocationPoint(String locationPoint) {
		this.locationPoint = locationPoint;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public BusinessInfo getBsi() {
		return bsi;
	}

	public void setBsi(BusinessInfo bsi) {
		this.bsi = bsi;
	}


    
	

}
