package com.qst.entity;
// Generated 2019-8-5 19:53:09 by Hibernate Tools 5.1.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCollect generated by hbm2java
 */
@Entity
@Table(name = "tb_collect")
public class TbCollect implements java.io.Serializable {

	private int id;
	private Integer UId;
	private Integer PId;
	private Date createTime;
    private TbPosition tbPosition;
    
	public TbCollect() {
	}

	public TbCollect(int id) {
		this.id = id;
	}

	public TbCollect(int id, Integer UId, Integer PId, Date createTime) {
		this.id = id;
		this.UId = UId;
		this.PId = PId;
		this.createTime = createTime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "u_id")
	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	@Column(name = "p_id")
	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "TbCollect [id=" + id + ", UId=" + UId + ", PId=" + PId + ", createTime=" + createTime + "]";
	}

	public TbPosition getTbPosition() {
		return tbPosition;
	}

	public void setTbPosition(TbPosition tbPosition) {
		this.tbPosition = tbPosition;
	}

	
}
