package com.qst.entity;
// Generated 2019-8-5 19:53:09 by Hibernate Tools 5.1.10.Final

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbPosition generated by hbm2java
 */
@Entity
@Table(name = "tb_position")
public class TbPosition implements java.io.Serializable {

	private int id;
	private String name;
	private Integer CId;
	private Integer salaryMin;
	private Integer salaryMax;
	private Integer category;
	private Integer type;
	private Integer address;
	private Integer education;
	private String tag;
	private Date endTime;
	private Date createTime;
	private String description;
	private Date updateTime;
	private Integer status;

	//多对一关联映射的公司属性
	private TbCompany company;
	
	//附加字段 0 普通，1浏览过，2已投递
	private int userStatus = 0;
	//附加收藏字段  0为没收藏  2为已收藏
	private int collectStatus=0;
	
	private String eTime;
	private String  cTime;
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	public TbPosition() {
	}

	public TbPosition(int id) {
		this.id = id;
	}

	public TbPosition(int id, String name, Integer CId, Integer salaryMin, Integer salaryMax, Integer type,
			Integer address, Integer education, String tag, Date createTime, String desc, Date updateTime,
			Integer status) {
		this.id = id;
		this.name = name;
		this.CId = CId;
		this.salaryMin = salaryMin;
		this.salaryMax = salaryMax;
		this.type = type;
		this.address = address;
		this.education = education;
		this.tag = tag;
		this.createTime = createTime;
		this.description = desc;
		this.updateTime = updateTime;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	
	@Column(name = "c_id")
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	@Column(name = "salary_min")
	public Integer getSalaryMin() {
		return this.salaryMin;
	}

	public void setSalaryMin(Integer salaryMin) {
		this.salaryMin = salaryMin;
	}

	@Column(name = "salary_max")
	public Integer getSalaryMax() {
		return this.salaryMax;
	}

	public void setSalaryMax(Integer salaryMax) {
		this.salaryMax = salaryMax;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "address")
	public Integer getAddress() {
		return this.address;
	}

	public void setAddress(Integer address) {
		this.address = address;
	}

	@Column(name = "education")
	public Integer getEducation() {
		return this.education;
	}

	public void setEducation(Integer education) {
		this.education = education;
	}
	
	public String getEducationStr(){
		switch (education) {
		case 0: return "无学历要求";
		case 1: return "高中";
		case 2: return "专科";
		case 3: return "本科";
		case 4: return "硕士";
		case 5: return "博士";
		default:
			break;
		}
		return "";
	}

	@Column(name = "tag")
	public String getTag() {
		return this.tag;
	}
	
	public String[] getTags(){
		if(this.tag != null)
			return this.tag.split(",");
		return new String[]{"可以"};
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "desc")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String desc) {
		this.description = desc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "TbPosition [id=" + id + ", name=" + name + ", CId=" + CId + ", salaryMin=" + salaryMin + ", salaryMax="
				+ salaryMax + ", type=" + type + ", address=" + address + ", education=" + education + ", tag=" + tag
				+ ", createTime=" + createTime + ", description=" + description + ", updateTime=" + updateTime
				+ ", status=" + status + "]";
	}

	public int getUserStatus() {
		return userStatus;
	}

	public void setUserStatus(int userStatus) {
		this.userStatus = userStatus;
	}
  
	public int getCollectStatus() {
		return collectStatus;
	}

	public void setCollectStatus(int collectStatus) {
		this.collectStatus = collectStatus;
	}

	public TbCompany getCompany() {
		return company;
	}

	public void setCompany(TbCompany company) {
		this.company = company;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getCategory() {
		return category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	public String geteTime() {
		if( endTime ==null){
			return "";
		}
		return sdf.format(endTime);
		
	}

	public void seteTime(String eTime) {
		this.eTime = sdf.format(endTime);
	}

	public String getcTime() {
		return sdf.format(createTime);
	}

	public void setcTime(String cTime) {
		this.cTime = sdf.format(createTime);
	}
 
}
