package com.qst.entity;
// Generated 2019-8-5 19:53:09 by Hibernate Tools 5.1.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbResumeFile generated by hbm2java
 */
@Entity
@Table(name = "tb_resume_file")
public class TbResumeFile implements java.io.Serializable {

	private int id;
	private String name;
	private Integer UId;
	private String url;
	private Integer status;

	public TbResumeFile() {
	}

	public TbResumeFile(int id) {
		this.id = id;
	}

	public TbResumeFile(int id, String name, Integer UId, String url, Integer status) {
		this.id = id;
		this.name = name;
		this.UId = UId;
		this.url = url;
		this.status = status;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "u_id")
	public Integer getUId() {
		return this.UId;
	}

	public void setUId(Integer UId) {
		this.UId = UId;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "TbResumeFile [id=" + id + ", name=" + name + ", UId=" + UId + ", url=" + url + ", status=" + status
				+ "]";
	}

}
