package com.qst.entity;
// Generated 2019-8-5 19:53:09 by Hibernate Tools 5.1.10.Final

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.qst.util.DateUtil;

/**
 * TbUser generated by hbm2java
 */

public class TbUser implements java.io.Serializable {

	private Integer id;
	private String phone;
	private String pwd;
	private String pwd1;
	private String pwd2;
	private String email;
	private String wechat;
	private String head;
	private String name;
	private Integer sex;
	private Date birthday;
	private Integer status;
	private Date ctatetime;
	private Integer visible;
	private String address;
	
	private TbResume resume;
	
	public TbUser() {
	}

	public TbUser(Integer id) {
		this.id = id;
	}

	public TbUser(Integer id, String phone, String pwd, String email, String wechat, String head, String name, Integer sex,
			Date birthday, Integer status, Date ctatetime, Integer visible) {
		this.id = id;
		this.phone = phone;
		this.pwd = pwd;
		this.email = email;
		this.wechat = wechat;
		this.head = head;
		this.name = name;
		this.sex = sex;
		this.birthday = birthday;
		this.status = status;
		this.ctatetime = ctatetime;
		this.visible = visible;
	}
	
 
	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}
	
	public String getPwd1() {
		return pwd1;
	}

	public void setPwd1(String pwd1) {
		this.pwd1 = pwd1;
	}
	public String getPwd2() {
		return pwd2;
	}

	public void setPwd2(String pwd2) {
		this.pwd2 = pwd2;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWechat() {
		return this.wechat;
	}

	public void setWechat(String wechat) {
		this.wechat = wechat;
	}

	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getSex() {
		return this.sex;
	}

	public void setSex(Integer sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
		/*this.birthday = DateUtil.getDateFormat(birthday);*/
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCtatetime() {
		return this.ctatetime;
	}

	public void setCtatetime(Date ctatetime) {
		this.ctatetime = ctatetime;
	}

	public Integer getVisible() {
		return this.visible;
	}

	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	@Override
	public String toString() {
		return "TbUser [id=" + id + ", phone=" + phone + ", pwd=" + pwd + ", email=" + email + ", wechat=" + wechat
				+ ", head=" + head + ", name=" + name + ", sex=" + sex + ", birthday=" + birthday + ", status=" + status
				+ ", ctatetime=" + ctatetime + ", visible=" + visible + "]";
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public TbResume getResume() {
		return resume;
	}

	public void setResume(TbResume resume) {
		this.resume = resume;
	}

}
